project:
  type: website
  output-dir: ../docs
  render:
    - "*.qmd"
    - "**/*.qmd"
    - "**/*.md"
    - "!drafts/*"
  
website:  
  title: "Bike share case-study"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: viz/visualizations.qmd
        text: Visualizations
      - href: data.qmd
        text: Data Sources
      - href: glossary.qmd
        text: Glossary  

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    css: styles.css       


